name: Deploy Im-Oei

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create config.js
        run: |
          cat > im-oei-v10/public/config.js <<'ENDCONFIG'
          export const FIREBASE_CONFIG = {
            apiKey:            "AIzaSyBJjzTASSDoezaH2lPTUP1Fn9jS6RR-OUo",
            authDomain:        "im-oei.firebaseapp.com",
            projectId:         "im-oei",
            storageBucket:     "im-oei.firebasestorage.app",
            messagingSenderId: "392812205535",
            appId:             "1:392812205535:web:65f6ce114feb3ce035a06a",
            measurementId:     "G-0LGSELSP0D"
          };
          export const LIFF_ID = "2009910221-ySbGklzJ";
          export const VAPID_PUBLIC_KEY = "BGZbGcsIuEzA5enjkAmik_kuZwvAsNGpsuEUj_p3TpJVaRSq0KnkxUlcthSnCT_rpZC4tg7eTQPq1v1FrArd3j0";
          export const RECAPTCHA_SITE_KEY = "6LfBotcsAAAAACxl8p6XtLXisjPH-XacxIXX-ZiC";
          export const RECAPTCHA_SITE_KEY = "6LfBotcsAAAAACxl8p6XtLXisjPH-XacxIXX-ZiC";
          window.LIFF_ID = "2009910221-ySbGklzJ";
          ENDCONFIG

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: im-oei
          entryPoint: im-oei-v10
